RESOURCES_DIR: resources
MULTI_WORKSPACES: False # True
WORKSPACES: [0, 1]
OS: windows # linux
VERBOSE: 1
REFRESH:
  MIN: 300
  MAX: 600
HEROES:
  STRATEGY: all # greens
  MIN: 1500
  MAX: 1800