RESOURCES_DIR: resources
ZOOM: 1.0 # 0.5
MULTI_WORKSPACES: False # True
WORKSPACES: [0, 1]
OS: windows # linux
VERBOSE: 1
REFRESH:
  MIN: 60
  MAX: 180
HEROES:
  STRATEGY: all # greens
  MIN: 1500
  MAX: 1800